Revert "scriptlets: build: Reduce build time by avoiding running tests"
The application failed to launch when patch is applied:

```output
Error: Unable to initialize main class com.madgag.git.bfg.cli.Main
Caused by: java.lang.NoClassDefFoundError: scala/Function0
```

This reverts commit f0ccd86f868d138da7eee4d6caf5b04ab81e2d8e.

Signed-off-by: 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>